### ISSUE TITLE
28 July Meeting Points

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/GemmaDE#29]
- Is there a documentation on Nathaniel's freeze and how it was generated?
- Starting from moving the necessary components to work as a package (data, dependencies etc) -> one of the aims and good for maintainability (eg. can't overwrite shiny functions if you want to work as a package)
- Note that current data generation relies on a mix of live API calls and nathaniel's freeze
- Should the resulting package be entirely self contained? There seems to be data sources we might not be allowed to share (drugbank)

**Comment by jsicherm** [comment]
My 2p, and some asterisks that I can think of:
1. I have a couple non-production forks of packages used in the original code (shinypanels, maybe async, maybe one other that I should have made note of in dependencies.R). This will likely complicate acceptance on Bioconductor, and packaging in general.
2. It's likely to work more efficiently on Linux machines due to some async usages IIRC, and I believe it also has non-R dependencies (specifically for Rfast IIRC) which may limit users
3. My personal opinion is that it would be nice to package up the enrichment algorithm aside from the Shiny app so that users can just run it programmatically without all the fat of the Shiny app (which introduces the majority of the hard-to-get-Bioc-approved stuff). Unless the big picture is to fully democratize access outside of just PavLab servers.

**Comment by oganm** [comment]
For your 3rd point, Paul's plan seems to involve making a package that makes API calls to a server on our end which runs the analysis. The main driver for this approach, to my understanding is the data size. It does make a few things easier such as keeping your own forks in without anyone complaining.
